# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: (Fake) Generate a version in MVNCentral

on:
  pull_request:
    types: [closed]
    branches: [develop]
  workflow_dispatch:
    inputs:
      manual_exec:
        description: 'Manually dispatch'
        type: choice
        required: true
        default: 'Manually'
        options:
          - Manually

jobs:
  Fake_Generate-a-snapshot-in-MVNCentral:
    if: ${{ github.event.pull_request.merged == true || github.event.inputs.environment == 'Manually' }}
    runs-on: ubuntu-latest
    steps:
    - name: Print merge message
      run: |
        echo PR #${{ github.event.number }} has been MERGED
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Setup Java JDK and Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Publish to Apache Maven Central
      run: mvn -B verify